---
title: 'Reliability, Maintainability, and Quality Management'
author: '<h3>Course Syllabus - 2018</h3>'
date: '<h3>MTWHF 0900-1200 USAF Expeditionary Center, Ft Dix, NJ (3.0 Credit Hours)</h3>'
output: 
  github_document:
    html_preview: yes
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { 
      root <- rprojroot::find_root(rprojroot::is_rstudio_project) ;
      rmarkdown::render(inputFile, 
                        encoding = encoding,  
                        output_file = file.path(root, 'README.md'))})
---

## Course Description

Creating and sustaining military capability is the purpose of military leadership and management. Reliability and maintainability (R&M) are component characteristics, which define the ability of a product to perform its specified functions throughout its operational life. Component R&M of the military system are primary determinants of military capability. This course teaches fundamental R&M concepts. Additionally, probability theory is discussed and employed as a tool to quantitatively define these concepts. Topics to be discussed include the measures, which quantitatively define component R&M, the relationship between R&M, and the prediction of R&M measures.  

## Course Objectives

Upon completion of this course each student shall be able to:

-	Understand and apply the fundamentals of the concepts of reliability, maintainability, and availability.

- Understand the use of probability theory to quantify R&M concepts.

- Understand and apply the measures which quantitatively define component R&M.
 
## Academic Integrity

Students found to be cheating will be referred for disciplinary action.  Cheating includes, but is not limited to, copying on exams, plagiarizing material from published sources, plagiarizing from former or current AFIT students, submitting someone else’s work as your own, or helping other students to cheat.  If you have any questions regarding what is permissible, please contact the professor for guidance.

## Pre-requisites & Co-requisites

None

## Instructor and Contact Information

Maj. Jason Freels  
Email: [**jason.freels@afit.edu**](mailto:jason.freels@afit.edu)  
Email: [**auburngrads@live.com**](mailto:auburngrads@live.com)  
Phone: (937) 255-3636 ext. 4676  
Cell:  (937) 430-6619  
Office: Bldg. 640, Rm. 205B  
Office hours: By appointment

## Resources

### Required resources

The required text for this course is

- Charles E. Ebeling  
[**An Introduction to Reliability and Maintainability Engineering**](http://www.waveland.com/browse.php?t=392&pgtitle=An+Introduction+to+Reliability+and+Maintainability+Engineering%3A+Second+Edition+by+Charles+E.+Ebeling)  
2nd ed., Waveland Press, Long Grove, IL 2010.  

### Optional resources

The following list includes references to more reliability-related resources that can be accessed online.  While not required, these references contain content that complements the material presented during this course.

- William Meeker and Luis Escobar  
[***Statistical Methods for Reliability Data***](https://www.amazon.com/Statistical-Methods-Reliability-William-Meeker/dp/0471143286)  
1st Ed., Wiley-Interscience, 1998

- Marvin. Rausand and Arlnot Hoyland  
[**System Reliability Theory: Models, Statistical Methods & Applications**](http://bcs.wiley.com/he-bcs/Books?action=index&itemId=047147133X&bcsId=9457)  
2nd ed., Wiley-Interscience, Hoboken, NJ 2004

- DOD Guide for Achieving Reliability, Availability, and Maintainability, 3 Aug 2005

- [**Bill Meeker's Homepage**](http://www.public.iastate.edu/~wqmeeker/homepage.html)

- [**Weibull.com - Reliability Engineering Resource Website**](http://www.weibull.com/)

- [**Reliasoft Corporation Homepage**](http://www.reliasoft.com/)

- [**NIST/SEMATECH e-Handbook of Statistical Methods**](http://itl.nist.gov/div898/handbook/)

- [**Defense Systems Information Analysis Center**](http://www.theriac.org/)

- [**Army Material Systems Analysis Activity**](http://web.amsaa.army.mil/home.html/)

## Course Schedule (Tentative)

```{r, echo=FALSE}
week  <- 1:10
chap  <- c('1, 2','3, 4','4, 5','6, 7','7, 8','N/A','7, 8','9, 10','15, 16, 17','N/A')
topic <- c('Course Overview<br/>Reliability Introduction<br/>Math Review',
           'Failure Models<br/>System Reliability',
           'Failure Models',
           'State Dependent Systems<br/>Physical Reliability Models',
           'Physical Reliability Models<br/>Design for Reliability<br/>Reliability Growth Testing',
           ' ',
           'Design for Reliability<br/>Reliability Growth Testing',
           'Maintainability<br/>Design for Maintainability',
           'Reliability in Manufacture<br/>Maintainability & Availability<br/>Reliability Management','')
notes <- c('HW 1 Assigned',
           ' ',
           'HW 1 Due<br/>HW 2 Assigned',
           ' ',
           'HW 2 Due<br/>HW 3 Assigned<br/>Project Topics Due',
           ' ',
           'HW 3 Due<br/>HW 4 Assigned',
           ' ',
           'HW 4 Due<br/>Review For Final',
           'Student Presentations<br/>Final Exam')
df <- data.frame(week, chap, topic, notes)
colnames(df) <- c('Week','Chapters','Topics Presented','Notes')
knitr::kable(df, format = 'markdown', align = 'l')
```

## Course Format

Class material is primarily presented in lecture format.

## Performance Evaluation

Your grade in this course will be calculated according to the following requirements and their respective weights.

- __HOMEWORK (33%):__  
Homework is due at the beginning of class on the day listed in the class schedule.  Each student must turn in their own solutions for each problem assigned - Unless other arrangements are approved by the instructor.  Solutions will be posted that evening.

- __PROJECT (33%):__  
Students, in teams of two, will prepare a class presentation on a topic relevant to reliability, maintainability, and availability.  Presentations should be about 20 minutes long.  Students may choose a relevant DoD topic or their own topic, approved by the professor.  Topics and teams are "first-come, first-served"  Topic presentations will include the topic's background and why it is important or relevant, a brief literature review of the research on this topic, a description and assessment of any quantitative reliability tools used, and a managerial assessment of why USAF leaders should know and care about it.  

> Project examples: Evaluation of the C-5 re-engining and reliability improvement program, a B-52 life extension program, F-35 software reliability, GM ignition switch failures,r automotive air bag failures, the Samsung Galaxy Note 7 failures, or electric car battery failures.

- __FINAL EXAM (33\%):__  
The final exam will test comprehension of the course material in the book and class presentations, and ability to analytically solve problems scoped similar to the homework.  The exam is closed book, closed notes.  Students may prepare a formula sheet, on 8 ½" x 11" paper, and use both the front and back.  Students will have two hours to finish the exam.

A student's final letter grade will be parsed out according to the table below.  This grading profile follows the the standard grading profile established by the institution. 

- (1.00 - 0.93]: A
- (0.93 - 0.90]: A-
- (0.90 - 0.87]: B+
- (0.87 - 0.83]: B
- (0.83 - 0.80]: B-
- (0.80 - 0.77]: C

## Important Policy Statements

### Academic Integrity Policy Statement

All students must adhere to the highest standards of academic integrity. Students are prohibited from engaging in plagiarism, cheating, misrepresentation, or any other act constituting a lack of academic integrity. Failure on the part of any individual to practice academic integrity is not condoned and will not be tolerated. Individuals who violate this policy are subject to adverse administrative action including disenrollment from school and disciplinary action. Individuals subject to the Uniform Code of Military Justice may be prosecuted under the UCMJ. Violations by government civilian employees may result in administrative disciplinary action without regard to otherwise applicable criminal or civil sanctions for violations of related laws. (References: Student Handbook, ENOI 36 – 107, Academic Integrity)

### Attendance Policy Statement

Attendance at all class sessions and exams is mandatory for military and civilians assigned to AFIT as full-time students except for extenuating circumstances. Part-time students are expected to attend scheduled classes, and absences should be explained to the instructor. The student should provide advance notice, if possible. Scheduled classes and exams are defined by the instructor and they are documented in the course schedule. (References: Student Handbook, Graduate School Catalog)

### Academic Grievance Policy Statement

AFIT and the Graduate School of Engineering and Management affirm the right of each student to resolve grievances with the Institution. Students are guaranteed the right of fair hearing and appeal in all matters of judgment of academic performance. Procedures are detailed in ENOI 36 – 138, Student Academic Performance Appeals.

## Additional Notes

### My Teaching Philosophy

As __AFIT graduates__, you should be expected to know how to approach and solve real-world problems AND present your results in a meaningful way so that decision makers can make defensible decisions.  

As __AFIT instructors__, we do a disservice to our students by not teaching new and improved ways to produce and share your results.  Further, we do a disservice by teaching you to solve problems using tools that you won't have access to after leaving AFIT.  Therefore, I re-built this course using the R/RStudio tool-chain to help you produce better results...faster.

### Challenge your instructor

Challenging your instructor can often be a good thing.  If you can't trip me up in this class from time to time, you're not trying.  Discussion leads to a more interesting class, so questions are always good.

### "How not to do Reliability"

Industry provides many examples of how not to do reliability.  Occasionally, we'll discuss these examples to highlight the result of applying poor reliability principles.
